nagios_config_file_path = "./examples/nagios/nagios.cfg"
poll_cron = "* * * * *"
batch_size = 50

[api]
upsert_endpoint = "https://api.seethrunetworks.com/api/v3/feed/update"
jwt_key_refresh_endpoint = "https://api.seethrunetworks.com/api/token"

[api.keys.default]
type = "jwt"
secret_key = "{! API_KEY_SECRET_KEY !}"
uuid = "{! API_KEY_UUID !}"

# Will expose the diagnostics feeds of services
[[exposures.services]]
    # This block applies to any services that match the conditions
    [exposures.services.match]
    service_description = "(?<service_description>.*)"

    # Defines the diagnostics feed for all services that this block found
    [exposures.services.feeds.diagnostic.is_running]
    organisation = { id = 1 }
    page = { id = 10 }
    space = { id = 9 }
    name = "Diagnostic Feed for {{service_description}}"

    # Defines the transparant feed for all services that this block found
    [exposures.services.feeds.transparent]
    organisation = { id = 1 }
    space = { id = 10 }
    page = { id = 10 }
    name = "Transparent Feed for {{service_description}}"

# Will expose the ping feed for a service with name PING
[[exposures.services]]
    [exposures.services.match]
    # This block applies to any services that match the conditions
    service_description = "PING"

    # Defines the transparent feed for the service with description 'PING'
    [exposures.services.feeds.transparent]
    organisation = { id = 1 }
    page = { id = 10 }
    space = { id = 9 }
    name = "PING (Transparent)"
    tags = [ "linux_kernel=5.19" ]

    # Defines the ping plugin feed for the service with description 'PING'
    [exposures.services.feeds.plugin.ping]
    organisation = { id = 1 }
    page = { id = 10 }
    space = { id = 9 }
    name = "PING"


[[exposures.hosts]]
    [exposures.hosts.match]
    host_name = ".*"

    [exposures.hosts.feeds.status]
    organisation = { id = 1 }
    page = { id = 10 }
    space = { id = 9 }
    name = "Status of '{{host_name}}'"
    tags = ["linux_kernel=5.19", "os debian", "host={{host_name}}"]